In [2]:
import torch
torch.__version__

'2.7.1+cpu'

- PyTorch

- PyTorch is an open source machine learning and deep learning framework.
- PyTorch allows you to manipulate and process data and write machine learning algorithms using Python code.

-# Introduction to tensors

Tensors are the fundamental building block of machine learning.
It writes data in numerical way.

Scalar : zero dimension tensor

In [14]:
scalar = torch.tensor(5)
print('scalar', scalar)
print(scalar.ndim) # prints the dimensions of a tensor; ndim()

# Retrieve number from Tensor item()
print('Retrieved no. from tensor :', scalar.item())

# A vector is a single dimension tensor but can contain many numbers.
vector = torch.tensor([2,5])
print('vector:', vector)
print(vector.ndim)

# Shape of Vector
print('shape:', vector.shape)

scalar tensor(5)
0
Retrieved no. from tensor : 5
vector: tensor([2, 5])
1
shape: torch.Size([2])


In [ ]:
# Tensor
Tensor = torch.tensor([[[7, 6, 3],
                        [3, 5, 1],
                        [2, 8, 5]]]) # 3d Tensor

""" Tensor = torch.tensor([[7, 6, 3],
                        [3, 5, 1],
                        [2, 8, 5]]) #2D Tensor """

print(Tensor)
# Trick: use the square bracket on the outside of one side counting trick 
print('dimension:', Tensor.ndim)
print(Tensor.shape) # The dimensions go outer to inner

tensor([[[7, 6, 3],
         [3, 5, 1],
         [2, 8, 5]]])
dimension: 3
torch.Size([1, 3, 3])


Some Notes:

- ML models such as neural networks manipulate and seek patterns within tensors.
- When building ML models with PyTorch, it's rare we'll create tensors by hand
- Instead, a machine learning model often starts out with large random tensors of numbers and adjusts these random numbers as it works through data to better represent it.
-

**Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...**

As a data scientist, you can define how the machine learning model starts (initialization), looks at data (representation) and updates (optimization) its random numbers.



In [22]:
# Create a tensor of random numbers

random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype

(tensor([[0.2179, 0.4869, 0.0500, 0.7345],
         [0.6402, 0.1215, 0.1211, 0.8675],
         [0.8624, 0.4604, 0.9976, 0.1926]]),
 torch.float32)

In [27]:
# Zeros and ones

zeros = torch.zeros(size=(3,4))
print(zeros)
print(zeros.dtype)

ones = torch.ones(size=(3,4))
print(ones)
print(ones.dtype)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
torch.float32
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.float32


In [29]:
# Creating a range and tensors like
# torch.arange(start, end, step)

# Create a range of values 0 to 10
range = torch.arange(start=0, end=10, step=1)
range


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
""" Sometimes you might want one tensor of a certain type with the same shape as another tensor.
For example, a tensor of all zeros with the same shape as a previous tensor.
To do so you can use torch.zeros_like(input) or torch.ones_like(input) which return a tensor filled with zeros or ones in the same shape as the input respectively. 
"""

# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=range) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])