In [23]:
import torch
torch.__version__

'2.7.1+cpu'

- PyTorch

- PyTorch is an open source machine learning and deep learning framework.
- PyTorch allows you to manipulate and process data and write machine learning algorithms using Python code.

-# Introduction to tensors

Tensors are the fundamental building block of machine learning.
It writes data in numerical way.

Scalar : zero dimension tensor

In [24]:
scalar = torch.tensor(5)
print('scalar', scalar)
print(scalar.ndim) # prints the dimensions of a tensor; ndim()

# Retrieve number from Tensor item()
print('Retrieved no. from tensor :', scalar.item())

# A vector is a single dimension tensor but can contain many numbers.
vector = torch.tensor([2,5])
print('vector:', vector)
print(vector.ndim)

# Shape of Vector
print('shape:', vector.shape)

scalar tensor(5)
0
Retrieved no. from tensor : 5
vector: tensor([2, 5])
1
shape: torch.Size([2])


In [25]:
# Tensor
Tensor = torch.tensor([[[7, 6, 3],
                        [3, 5, 1],
                        [2, 8, 5]]]) # 3d Tensor

""" Tensor = torch.tensor([[7, 6, 3],
                        [3, 5, 1],
                        [2, 8, 5]]) #2D Tensor """

print(Tensor)
# Trick: use the square bracket on the outside of one side counting trick 
print('dimension:', Tensor.ndim)
print(Tensor.shape) # The dimensions go outer to inner

tensor([[[7, 6, 3],
         [3, 5, 1],
         [2, 8, 5]]])
dimension: 3
torch.Size([1, 3, 3])


Some Notes:

- ML models such as neural networks manipulate and seek patterns within tensors.
- When building ML models with PyTorch, it's rare we'll create tensors by hand
- Instead, a machine learning model often starts out with large random tensors of numbers and adjusts these random numbers as it works through data to better represent it.
-

**Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...**

As a data scientist, you can define how the machine learning model starts (initialization), looks at data (representation) and updates (optimization) its random numbers.



In [26]:
# Create a tensor of random numbers

random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype

(tensor([[0.9841, 0.8126, 0.2846, 0.3117],
         [0.1373, 0.8890, 0.0596, 0.9922],
         [0.2614, 0.5333, 0.1984, 0.5145]]),
 torch.float32)

In [27]:
# Zeros and ones

zeros = torch.zeros(size=(3,4))
print(zeros)
print(zeros.dtype)

ones = torch.ones(size=(3,4))
print(ones)
print(ones.dtype)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
torch.float32
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.float32


In [28]:
# Creating a range and tensors like
# torch.arange(start, end, step)

# Create a range of values 0 to 10
range = torch.arange(start=0, end=10, step=1)
range


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
""" Sometimes you might want one tensor of a certain type with the same shape as another tensor.
For example, a tensor of all zeros with the same shape as a previous tensor.
To do so you can use torch.zeros_like(input) or torch.ones_like(input) which return a tensor filled with zeros or ones in the same shape as the input respectively. 
"""

# Can also create a tensor of zeros similar to another tensor
similar = torch.zeros_like(input=range) # will have same shape
similar

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor datatypes

- There are many different tensor datatypes available in PyTorch. Some are specific for CPU and some are better for GPU.

- Generally if you see torch.cuda anywhere, the tensor is being used for GPU (since Nvidia GPUs use a computing toolkit called CUDA).

- The most common type (and generally the default) is torch.float32 or torch.float. This is referred to as "32-bit floating point".

- But there's also 16-bit floating point (torch.float16 or torch.half) and 64-bit floating point (torch.float64 or torch.double).

- Lower precision datatypes are generally faster to compute on but sacrifice some performance on evaluation metrics like accuracy (faster to compute but less accurate)



In [30]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [31]:
""" Aside from shape issues (tensor shapes don't match up), two of the other most common issues we'll come across in PyTorch are datatype and device issues.
For example, one of tensors is torch.float32 and the other is torch.float16 (PyTorch often likes tensors to be the same format).
Or one of your tensors is on the CPU and the other is on the GPU (PyTorch likes calculations between tensors to be on the same device). 
"""
# dtype=torch.float16
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

In [32]:
# Getting information from tensors
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

# Note: When you encounter errors...do this --> "what shape are my tensors? what datatype are 
# they and where are they stored? what shape, what datatype, where where where"

tensor([[0.2255, 0.3607, 0.7198, 0.8185],
        [0.9351, 0.3992, 0.9038, 0.4590],
        [0.8850, 0.4437, 0.2538, 0.5303]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Manipulating Tensors

In deep learning, data (images, text, video, audio, protein structures, etc) gets represented as tensors.

A model learns by investigating those tensors and performing a series of operations (could be 1,000,000s+) on tensors to create a representation of the patterns in the input data.

These operations are often a wonderful dance between:

Addition,
Substraction,
Multiplication (element-wise),
Division,
Matrix multiplication,
And that's it. Sure there are a few more here and there but these are the basic building blocks of neural networks.

Stacking these building blocks in the right way, you can create the most sophisticated of neural networks (just like lego!)

In [33]:
tensor = torch.tensor([1, 2, 3])
print(tensor + 100)
print(tensor * 100) # it's more common to use the operator symbols like * instead of torch.mul()
print(tensor / 100)
print(tensor - 100)
# original tensor will be unchanged

tensor([101, 102, 103])
tensor([100, 200, 300])
tensor([0.0100, 0.0200, 0.0300])
tensor([-99, -98, -97])


### Matrix multiplication (is all you need)
One of the most common operations in machine learning and deep learning algorithms (like neural networks) is matrix multiplication.

- PyTorch implements matrix multiplication functionality in the **torch.matmul()** method.

- The main two rules for matrix multiplication to remember are:

- The inner dimensions must match:

        (3, 2) @ (3, 2) won't work

        (2, 3) @ (3, 2) will work

        (3, 2) @ (2, 3) will work

- The resulting matrix has the shape of the outer dimensions:

        (2, 3) @ (3, 2) -> (2, 2)

        (3, 2) @ (2, 3) -> (3, 3)

- Note: "@" in Python is the symbol for **matrix multiplication**.

In [34]:
import torch
tensor = torch.tensor([1, 2, 3])
print(tensor.shape)
print('Element-wise multiplication (tensor * tensor):', tensor*tensor)
print('Matrix multiplication (tensor.matmul(tensor)):', tensor.matmul(tensor)) # torch.matmul(tensor, tensor)
#torch.matmul(tensor, tensor)
# tensor @ tensor # not recommended
# Note: The difference between element-wise multiplication and matrix multiplication is the addition of values.
# The in-built torch.matmul() method is faster instead of doing by hand

torch.Size([3])
Element-wise multiplication (tensor * tensor): tensor([1, 4, 9])
Matrix multiplication (tensor.matmul(tensor)): tensor(14)


In [35]:
# One of the most common errors in deep learning (shape errors)
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32) # 3 x 2 Matrix

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)  # 3 x 2 Matrix

torch.matmul(tensor_A, tensor_B) # (this will error) as matrix inner dimension should be same

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
# Above can be corrected using following

print(tensor_A) # 3x2
print(tensor_B.T) # 2x3 (.T is transpose of a matrix)
torch.matmul(tensor_A, tensor_B.T) # torch.mm also can be used

# Note: A matrix multiplication like this is also referred to as the dot product of two matrices.

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Neural networks are full of matrix multiplications and dot products.

- The torch.nn.Linear() module, also known as a **feed-forward layer or fully connected layer**, implements a matrix multiplication between an input x and a weights matrix A
y = x.A^T + b

Where:

x is the input to the layer (deep learning is a stack of layers like torch.nn.Linear() and others on top of each other).

A is the weights matrix created by the layer, this starts out as random numbers that get adjusted as a neural network learns to better represent patterns in the data (notice the "T", that's because the weights matrix gets transposed).

Note: You might also often see W or another letter like X used to showcase the weights matrix.
b is the bias term used to slightly offset the weights and inputs.

y is the output (a manipulation of the input in the hopes to discover patterns in it).

This is a linear function (something like $y = mx+b$), and can be used to draw a straight line!



In [ ]:
# torch.nn.Linear()
# A weights matrix (A) of size [out_features, in_features]
# A bias vector (b) of size [out_features]
import torch
torch.manual_seed(42)

linear = torch.nn.Linear(in_features=2, out_features=6)
x = tensor_A
output = linear(x)

print(f"Input size: {x.shape}\n")
print(f"Output:\n{output}\n")
print(f"Output size: {output.shape}")


Input size: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output size: torch.Size([3, 6])


In [ ]:
# Finding the min, max, mean, sum, etc
import torch
# Creating Tensor
x = torch.arange(0, 50, 5)
print(x)
print('Min:', x.min().item())
print('Max:', x.max().item())
print('Mean:', x.type(torch.float32).mean().item())
print('Sum:', x.sum().item())

# Note: tensor.item() will give the value, otherwise it will give values in form tensor(value)
# Note: You may find some methods such as torch.mean() require tensors to be in torch.float32 (the most common) or another specific datatype, otherwise the operation will fail.

# Can be done using torch methods as follows also:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)


# Note: You can change the datatypes of tensors using torch.Tensor.type(dtype=None) where the dtype parameter is the datatype we'd like to use

tensor_float16 = tensor.type(torch.float16)
print(tensor_float16)
tensor_int8 = tensor.type(torch.int8)
print(tensor_int8)

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])
Min: 0
Max: 45
Mean: 22.5
Sum: 225
tensor([1., 2., 3.], dtype=torch.float16)
tensor([1, 2, 3], dtype=torch.int8)


In [ ]:
""" Positional min/max
You can also find the index of a tensor where the max or minimum occurs with torch.argmax() and 
torch.argmin() respectively. """
# This is helpful incase you just want the position where the highest (or lowest) value is and not the actual value itself

print('Index where max value occurs: ', x.argmax().item())
print('Index where min value occurs: ', x.argmin().item())


Index where max value occurs:  9
Index where min value occurs:  0


### Reshaping, stacking, squeezing and unsqueezing

| **Method** | **One-line description** |
|-------------|---------------------------|
| `torch.reshape(input, shape)` | Reshapes input to `shape` (if compatible), can also use `torch.Tensor.reshape()`. |
| `Tensor.view(shape)` | Returns a view of the original tensor in a different shape but shares the same data as the original tensor. |
| `torch.stack(tensors, dim=0)` | Concatenates a sequence of tensors along a new dimension (`dim`), all tensors must be same size. |
| `torch.squeeze(input)` | Squeezes input to remove all the dimensions with value `1`. |
| `torch.unsqueeze(input, dim)` | Returns input with a dimension value of `1` added at `dim`. |
| `torch.permute(input, dims)` | Returns a view of the original input with its dimensions permuted (rearranged) to `dims`. |

**Why do any of these?**

- Because deep learning models (neural networks) are all about manipulating tensors in some way. And because of the rules of matrix multiplication, if you've got shape mismatches, you'll run into errors. These methods help you make sure the right elements of your tensors are mixing with the right elements of other tensors.

In [ ]:
import torch

x = torch.arange(1, 8)
print(x)
print(x.shape)

# Adding extra dimension
x_reshaped = x.reshape(1,7)
print('x_reshaped:', x_reshaped)
print(x_reshaped.shape)

# Change view
z = x.view(7, 1)
print(z)
z[2,0] = 456
print('original (changes value in the data, but shape remains the same): \n ', x)
print(z)

# Changing the view of a tensor with torch.view() really only creates a new view of the same tensor.
# So changing the view changes the original tensor too.

tensor([1, 2, 3, 4, 5, 6, 7])
torch.Size([7])
x_reshaped: tensor([[1, 2, 3, 4, 5, 6, 7]])
torch.Size([1, 7])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7]])
original (changes value in the data, but shape remains the same): 
  tensor([  1,   2, 456,   4,   5,   6,   7])
tensor([[  1],
        [  2],
        [456],
        [  4],
        [  5],
        [  6],
        [  7]])


In [ ]:
# Stack tensors on top of each other
x_stacked_dim0 = torch.stack([x, x, x, x, x], dim=0)
x_stacked_dim1 = torch.stack([x, x, x, x, x], dim=1)
print(x)
print('dim 0: (stacked over each other)\n', x_stacked_dim0)
print('\n dim 1: (transposed and stack side by side) \n', x_stacked_dim1)

tensor([  1,   2, 456,   4,   5,   6,   7])
dim 0: (stacked over each other)
 tensor([[  1,   2, 456,   4,   5,   6,   7],
        [  1,   2, 456,   4,   5,   6,   7],
        [  1,   2, 456,   4,   5,   6,   7],
        [  1,   2, 456,   4,   5,   6,   7],
        [  1,   2, 456,   4,   5,   6,   7]])

 dim 1: (transposed and stack side by side) 
 tensor([[  1,   1,   1,   1,   1],
        [  2,   2,   2,   2,   2],
        [456, 456, 456, 456, 456],
        [  4,   4,   4,   4,   4],
        [  5,   5,   5,   5,   5],
        [  6,   6,   6,   6,   6],
        [  7,   7,   7,   7,   7]])


In [ ]:
# Remove extra dimension from x_reshaped

x_squeezed = x_reshaped.squeeze()
print(x_squeezed)
print(x_squeezed.shape)

tensor([  1,   2, 456,   4,   5,   6,   7])
torch.Size([7])


In [ ]:
# Add extra dimension with unsqueeze

x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(x_unsqueezed)
print(x_unsqueezed.shape)

tensor([[  1,   2, 456,   4,   5,   6,   7]])
torch.Size([1, 7])


In [ ]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

# Note: Because permuting returns a view (shares the same data as the original), 
# the values in the permuted tensor will be the same as the original tensor and 
# if you change the values in the view, it will change the values of the original.


Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
# Indexing
# It is similar to indexing on Python lists or Numpy arrays

import torch
x = torch.arange(1, 10).reshape(1,3,3)
print(x, x.shape)

# Indexing bracket by bracket
print('1st Square bracket: \n', x[0])
print('2nd Square bracket: \n', x[0][0])
print('3rd Square bracket: \n', x[0][0][0])


tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]) torch.Size([1, 3, 3])
1st Square bracket: 
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
2nd Square bracket: 
 tensor([1, 2, 3])
3rd Square bracket: 
 tensor(1)


In [ ]:
""" Think of the three dimensions as:
dim0 = sample / batch dimension (index 0 has one sample),
dim1 = row (3 rows: indices 0,1,2),
dim2 = column (3 cols: indices 0,1,2)."""

# Get all values of 0th dimension and the 0 index of 1st dimension
print(x[:, 0])

# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
print(x[:, :, 1])

# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
print(x[:, 1, 1])

# Get index 0 of 0th and 1st dimension and all values of 2nd dimension 
print(x[0, 0, :]) # same as x[0][0]


tensor([[1, 2, 3]])
tensor([[2, 5, 8]])
tensor([5])
tensor([1, 2, 3])


In [ ]:
# PyTorch tensors & NumPy
""" The two main methods to use for NumPy to PyTorch (and back again) are:

torch.from_numpy(ndarray) - NumPy array -> PyTorch tensor.
torch.Tensor.numpy() - PyTorch tensor -> NumPy array. """

import torch
import numpy as np

array = np.arange(1, 10)
tensor = torch.from_numpy(array)
array, tensor

# Note: By default, NumPy arrays are created with the datatype float64 and if you convert it 
# to a PyTorch tensor, it'll keep the same datatype (as above)
# tensor = torch.from_numpy(array).type(torch.float32) ==> as mostly tensors are in float32 form

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32))

In [41]:
# tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [43]:
## Reproducibility

import torch
import random

rand_seed = 20
torch.manual_seed(rand_seed)
tensor_A = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called
# Without this, tensor_A would be different to tensor_B 
torch.manual_seed(rand_seed)
tensor_B = torch.rand(3,4)

print('Tensor_A :\n', tensor_A)
print('\nTensor_B :\n', tensor_B)

Tensor_A :
 tensor([[0.5615, 0.1774, 0.8147, 0.3295],
        [0.2319, 0.7832, 0.8544, 0.1012],
        [0.1877, 0.9310, 0.0899, 0.3156]])

Tensor_B :
 tensor([[0.5615, 0.1774, 0.8147, 0.3295],
        [0.2319, 0.7832, 0.8544, 0.1012],
        [0.1877, 0.9310, 0.0899, 0.3156]])


In [45]:
# Getting PyTorch to run on the GPU
!nvidia-smi

Sun Oct 26 08:45:57 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 581.29                 Driver Version: 581.29         CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1650      WDDM  |   00000000:01:00.0  On |                  N/A |
| N/A   41C    P8              1W /   50W |     317MiB /   4096MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [2]:
# Check for GPU

import torch
torch.cuda.is_available()

True

In [3]:
# Count number of devices
torch.cuda.device_count()

1