# 02_jacobi_convergence_analysis

Write a Python program that simulates and analyzes the convergence behavior of an iterative linear solver.

1. Implement a Jacobi iterative solver to solve a small, diagonally dominant linear system ( A x = b ).
2. Record the residual norm ( r_k = | b - A x_k |_2 ) at each iteration to track the convergence history.
3. Generate a synthetic exponential decay curve representing ideal convergence and compare it with the actual solver residuals.
4. Plot both convergence histories on a semilogarithmic scale.
5. Compute and report the average convergence rate based on the residual data.


In [ ]:
import numpy as np 

# Sample Test System which is stable and solution is known
a = np.array([[4, -1, 0, 0],
        [-1, 4, -1, 0],
        [0, -1, 4, 1],
        [0, 0, -1, 3]])

b = np.array([15, 10, 10, 10])

def jacobi(a, b, n, x=None):
    # Initial guess
    if x in None:
        x = zeros(len(a[0]))
    
    

[[ 4 -1  0  0]
 [-1  4 -1  0]
 [ 0 -1  4  1]
 [ 0  0 -1  3]]
